export type CryptoCategory = 'layer1' | 'layer2' | 'stablecoin' | 'memecoin' | 'defi' | 'infrastructure' | 'gaming' | 'privacy' | 'ai' | 'other';
export type CryptoNetwork = 'bitcoin' | 'ethereum' | 'binance' | 'solana' | 'ripple' | 'cardano' | 'polkadot' | 'avalanche' | 'polygon' | 'arbitrum' | 'optimism' | 'near' | 'sui' | 'aptos' | 'cosmos' | 'tron' | 'ton' | 'stellar' | 'monero' | 'filecoin' | 'vechain' | 'hedera' | 'icp';
export type MarketTrend = 'bullish' | 'bearish' | 'sideways' | 'volatile';
export type RiskLevel = 'low' | 'medium' | 'high' | 'extreme';

export interface CryptoMarketData {
  currentPrice: number;
  marketCap: number;
  volume24h: number;
  rank: number;
  circulatingSupply: number;
  maxSupply?: number;
  change24h: number;
  change7d: number;
  change30d: number;
  volatility: number;
  trend: MarketTrend;
  lastUpdated: string;
}

export interface CryptoWalletConfig {
  addressPrefix: string;
  addressLength: number;
  decimals: number;
  displayPrecision: number;
  minTransfer: number;
  maxTransfer: number;
  minDeposit: number;
  minWithdrawal: number;
  maxWithdrawal: number;
  networkFee: number;
  estimatedConfirmationTime: string;
  qrCodeSupported: boolean;
}

export interface CryptoTradingConfig {
  buyEnabled: boolean;
  sellEnabled: boolean;
  swapEnabled: boolean;
  tradingEnabled: boolean;
  supportedDurations: number[];
  minTrade: number;
  maxTrade: number;
  profitMultipliers: number[];
  riskLevel: RiskLevel;
  spreadPercentage: number;
}

export interface CryptoUIConfig {
  primaryColor: string;
  secondaryColor: string;
  gradientStart: string;
  gradientEnd: string;
  glowColor: string;
  chartColor: string;
  backgroundColor: string;
  icon: string;
}

export interface CryptoPortfolioConfig {
  defaultBalance: number;
  allocationType: 'primary' | 'secondary' | 'alternative';
  recommendedAllocation: number;
  riskRating: number;
}

export interface Cryptocurrency {
  id: string;
  symbol: string;
  name: string;
  fullName: string;
  category: CryptoCategory;
  network: CryptoNetwork;
  wallet: CryptoWalletConfig;
  marketData: CryptoMarketData;
  trading: CryptoTradingConfig;
  ui: CryptoUIConfig;
  portfolio: CryptoPortfolioConfig;
  website?: string;
  whitepaper?: string;
  founded?: number;
  description?: string;
}

export const CRYPTOCURRENCIES: Record<string, Cryptocurrency> = {
  BTC: {
    id: 'bitcoin',
    symbol: 'BTC',
    name: 'Bitcoin',
    fullName: 'Bitcoin',
    category: 'layer1',
    network: 'bitcoin',
    wallet: {
      addressPrefix: '1',
      addressLength: 34,
      decimals: 8,
      displayPrecision: 4,
      minTransfer: 0.001,
      maxTransfer: 100,
      minDeposit: 0.0001,
      minWithdrawal: 0.0005,
      maxWithdrawal: 50,
      networkFee: 0.0001,
      estimatedConfirmationTime: '10-30 minutes',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 45250.50,
      marketCap: 888000000000,
      volume24h: 28500000000,
      rank: 1,
      circulatingSupply: 21000000,
      maxSupply: 21000000,
      change24h: 2.5,
      change7d: 5.2,
      change30d: -1.8,
      volatility: 3.2,
      trend: 'bullish',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 0.001,
      maxTrade: 10,
      profitMultipliers: [1.5, 2, 2.5, 3],
      riskLevel: 'high',
      spreadPercentage: 0.5,
    },
    ui: {
      primaryColor: '#F7931A',
      secondaryColor: '#000000',
      gradientStart: '#F7931A',
      gradientEnd: '#FFB81C',
      glowColor: '#FFD700',
      chartColor: '#F7931A',
      backgroundColor: '#1a1a1a',
      icon: '₿',
    },
    portfolio: {
      defaultBalance: 0.25,
      allocationType: 'primary',
      recommendedAllocation: 40,
      riskRating: 7,
    },
    founded: 2009,
    description: 'The first and largest cryptocurrency by market cap',
  },
  ETH: {
    id: 'ethereum',
    symbol: 'ETH',
    name: 'Ethereum',
    fullName: 'Ethereum',
    category: 'layer1',
    network: 'ethereum',
    wallet: {
      addressPrefix: '0x',
      addressLength: 42,
      decimals: 18,
      displayPrecision: 2,
      minTransfer: 0.01,
      maxTransfer: 1000,
      minDeposit: 0.001,
      minWithdrawal: 0.01,
      maxWithdrawal: 500,
      networkFee: 0.01,
      estimatedConfirmationTime: '12-30 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 2850.75,
      marketCap: 342000000000,
      volume24h: 18200000000,
      rank: 2,
      circulatingSupply: 120000000,
      change24h: 3.2,
      change7d: 6.1,
      change30d: 2.5,
      volatility: 3.5,
      trend: 'bullish',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 0.01,
      maxTrade: 100,
      profitMultipliers: [1.4, 2, 2.8, 3.5],
      riskLevel: 'high',
      spreadPercentage: 0.3,
    },
    ui: {
      primaryColor: '#627EEA',
      secondaryColor: '#000000',
      gradientStart: '#627EEA',
      gradientEnd: '#9CA3FF',
      glowColor: '#00D4FF',
      chartColor: '#627EEA',
      backgroundColor: '#1a1a2e',
      icon: 'Ξ',
    },
    portfolio: {
      defaultBalance: 5,
      allocationType: 'primary',
      recommendedAllocation: 25,
      riskRating: 7,
    },
    founded: 2015,
    description: 'Smart contract platform and decentralized applications',
  },
  USDT: {
    id: 'tether',
    symbol: 'USDT',
    name: 'Tether',
    fullName: 'Tether USDT',
    category: 'stablecoin',
    network: 'ethereum',
    wallet: {
      addressPrefix: '0x',
      addressLength: 42,
      decimals: 6,
      displayPrecision: 2,
      minTransfer: 1,
      maxTransfer: 1000000,
      minDeposit: 10,
      minWithdrawal: 10,
      maxWithdrawal: 500000,
      networkFee: 1,
      estimatedConfirmationTime: '12-30 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 1.0,
      marketCap: 135000000000,
      volume24h: 95000000000,
      rank: 3,
      circulatingSupply: 135000000000,
      change24h: 0.0,
      change7d: 0.02,
      change30d: -0.01,
      volatility: 0.1,
      trend: 'sideways',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 10,
      maxTrade: 100000,
      profitMultipliers: [1.1, 1.2, 1.3, 1.5],
      riskLevel: 'low',
      spreadPercentage: 0.1,
    },
    ui: {
      primaryColor: '#26A17B',
      secondaryColor: '#000000',
      gradientStart: '#26A17B',
      gradientEnd: '#34C46E',
      glowColor: '#00FF00',
      chartColor: '#26A17B',
      backgroundColor: '#001a00',
      icon: '₮',
    },
    portfolio: {
      defaultBalance: 5000,
      allocationType: 'primary',
      recommendedAllocation: 20,
      riskRating: 1,
    },
    description: 'USD-backed stablecoin',
  },
  BNB: {
    id: 'binance-coin',
    symbol: 'BNB',
    name: 'Binance Coin',
    fullName: 'Binance Coin',
    category: 'layer1',
    network: 'binance',
    wallet: {
      addressPrefix: 'bnb',
      addressLength: 42,
      decimals: 18,
      displayPrecision: 2,
      minTransfer: 0.01,
      maxTransfer: 500,
      minDeposit: 0.01,
      minWithdrawal: 0.01,
      maxWithdrawal: 250,
      networkFee: 0.005,
      estimatedConfirmationTime: '5-15 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 612.45,
      marketCap: 92000000000,
      volume24h: 2100000000,
      rank: 4,
      circulatingSupply: 150000000,
      change24h: 2.8,
      change7d: 4.5,
      change30d: 1.2,
      volatility: 3.1,
      trend: 'bullish',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 0.1,
      maxTrade: 50,
      profitMultipliers: [1.3, 1.8, 2.2, 2.8],
      riskLevel: 'medium',
      spreadPercentage: 0.25,
    },
    ui: {
      primaryColor: '#F3BA2F',
      secondaryColor: '#000000',
      gradientStart: '#F3BA2F',
      gradientEnd: '#FFD700',
      glowColor: '#FFEB3B',
      chartColor: '#F3BA2F',
      backgroundColor: '#1a1800',
      icon: '⬟',
    },
    portfolio: {
      defaultBalance: 2,
      allocationType: 'primary',
      recommendedAllocation: 10,
      riskRating: 6,
    },
    founded: 2017,
    description: 'Binance blockchain native token',
  },
  SOL: {
    id: 'solana',
    symbol: 'SOL',
    name: 'Solana',
    fullName: 'Solana',
    category: 'layer1',
    network: 'solana',
    wallet: {
      addressPrefix: 'So',
      addressLength: 44,
      decimals: 9,
      displayPrecision: 2,
      minTransfer: 0.01,
      maxTransfer: 10000,
      minDeposit: 0.1,
      minWithdrawal: 0.1,
      maxWithdrawal: 5000,
      networkFee: 0.00025,
      estimatedConfirmationTime: '400ms',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 145.32,
      marketCap: 65000000000,
      volume24h: 3800000000,
      rank: 5,
      circulatingSupply: 447000000,
      change24h: 4.2,
      change7d: 8.5,
      change30d: 12.3,
      volatility: 4.2,
      trend: 'bullish',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 1,
      maxTrade: 500,
      profitMultipliers: [1.5, 2.2, 3, 4],
      riskLevel: 'high',
      spreadPercentage: 0.4,
    },
    ui: {
      primaryColor: '#14F195',
      secondaryColor: '#000000',
      gradientStart: '#14F195',
      gradientEnd: '#00D4FF',
      glowColor: '#00FF88',
      chartColor: '#14F195',
      backgroundColor: '#001a0f',
      icon: '◎',
    },
    portfolio: {
      defaultBalance: 10,
      allocationType: 'primary',
      recommendedAllocation: 8,
      riskRating: 8,
    },
    founded: 2020,
    description: 'High-speed blockchain platform',
  },
  XRP: {
    id: 'ripple',
    symbol: 'XRP',
    name: 'Ripple',
    fullName: 'XRP',
    category: 'infrastructure',
    network: 'ripple',
    wallet: {
      addressPrefix: 'r',
      addressLength: 34,
      decimals: 6,
      displayPrecision: 2,
      minTransfer: 0.1,
      maxTransfer: 100000,
      minDeposit: 1,
      minWithdrawal: 1,
      maxWithdrawal: 50000,
      networkFee: 0.00001,
      estimatedConfirmationTime: '3-5 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 2.45,
      marketCap: 135000000000,
      volume24h: 1500000000,
      rank: 6,
      circulatingSupply: 55000000000,
      maxSupply: 100000000000,
      change24h: 1.5,
      change7d: 3.2,
      change30d: -2.1,
      volatility: 2.8,
      trend: 'sideways',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 1,
      maxTrade: 50000,
      profitMultipliers: [1.2, 1.6, 2, 2.5],
      riskLevel: 'medium',
      spreadPercentage: 0.3,
    },
    ui: {
      primaryColor: '#0066CC',
      secondaryColor: '#000000',
      gradientStart: '#0066CC',
      gradientEnd: '#0099FF',
      glowColor: '#00CCFF',
      chartColor: '#0066CC',
      backgroundColor: '#000d1a',
      icon: '✕',
    },
    portfolio: {
      defaultBalance: 500,
      allocationType: 'secondary',
      recommendedAllocation: 5,
      riskRating: 5,
    },
    founded: 2012,
    description: 'Real-time settlement network',
  },
  DOGE: {
    id: 'dogecoin',
    symbol: 'DOGE',
    name: 'Dogecoin',
    fullName: 'Dogecoin',
    category: 'memecoin',
    network: 'bitcoin',
    wallet: {
      addressPrefix: 'D',
      addressLength: 34,
      decimals: 8,
      displayPrecision: 4,
      minTransfer: 1,
      maxTransfer: 1000000,
      minDeposit: 1,
      minWithdrawal: 1,
      maxWithdrawal: 500000,
      networkFee: 0.01,
      estimatedConfirmationTime: '1 minute',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 0.385,
      marketCap: 58000000000,
      volume24h: 1200000000,
      rank: 8,
      circulatingSupply: 150000000000,
      change24h: 3.5,
      change7d: 7.2,
      change30d: 5.8,
      volatility: 5.1,
      trend: 'bullish',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 10,
      maxTrade: 100000,
      profitMultipliers: [1.6, 2.4, 3.2, 4.5],
      riskLevel: 'extreme',
      spreadPercentage: 0.6,
    },
    ui: {
      primaryColor: '#C1A12B',
      secondaryColor: '#000000',
      gradientStart: '#C1A12B',
      gradientEnd: '#FFD700',
      glowColor: '#FFED4E',
      chartColor: '#C1A12B',
      backgroundColor: '#1a1500',
      icon: '🐶',
    },
    portfolio: {
      defaultBalance: 1000,
      allocationType: 'alternative',
      recommendedAllocation: 3,
      riskRating: 9,
    },
    founded: 2013,
    description: 'Meme-inspired cryptocurrency',
  },
  LTC: {
    id: 'litecoin',
    symbol: 'LTC',
    name: 'Litecoin',
    fullName: 'Litecoin',
    category: 'layer1',
    network: 'bitcoin',
    wallet: {
      addressPrefix: 'L',
      addressLength: 34,
      decimals: 8,
      displayPrecision: 4,
      minTransfer: 0.01,
      maxTransfer: 1000,
      minDeposit: 0.1,
      minWithdrawal: 0.1,
      maxWithdrawal: 500,
      networkFee: 0.001,
      estimatedConfirmationTime: '2-4 minutes',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 142.56,
      marketCap: 23000000000,
      volume24h: 1100000000,
      rank: 12,
      circulatingSupply: 161000000,
      maxSupply: 84000000,
      change24h: 2.1,
      change7d: 4.8,
      change30d: 1.3,
      volatility: 3.3,
      trend: 'bullish',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 0.1,
      maxTrade: 100,
      profitMultipliers: [1.4, 2, 2.6, 3.2],
      riskLevel: 'medium',
      spreadPercentage: 0.4,
    },
    ui: {
      primaryColor: '#345D9D',
      secondaryColor: '#000000',
      gradientStart: '#345D9D',
      gradientEnd: '#5A8DBD',
      glowColor: '#6BA3D0',
      chartColor: '#345D9D',
      backgroundColor: '#1a0f2e',
      icon: 'Ł',
    },
    portfolio: {
      defaultBalance: 5,
      allocationType: 'secondary',
      recommendedAllocation: 4,
      riskRating: 6,
    },
    founded: 2011,
    description: 'Faster Bitcoin alternative',
  },
  TRX: {
    id: 'tron',
    symbol: 'TRX',
    name: 'TRON',
    fullName: 'TRON',
    category: 'layer1',
    network: 'tron',
    wallet: {
      addressPrefix: 'T',
      addressLength: 34,
      decimals: 6,
      displayPrecision: 2,
      minTransfer: 1,
      maxTransfer: 100000,
      minDeposit: 1,
      minWithdrawal: 1,
      maxWithdrawal: 50000,
      networkFee: 0,
      estimatedConfirmationTime: '3 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 0.328,
      marketCap: 35000000000,
      volume24h: 2100000000,
      rank: 11,
      circulatingSupply: 106000000000,
      change24h: 2.8,
      change7d: 5.4,
      change30d: 3.2,
      volatility: 3.5,
      trend: 'bullish',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 100,
      maxTrade: 50000,
      profitMultipliers: [1.3, 1.9, 2.5, 3.3],
      riskLevel: 'medium',
      spreadPercentage: 0.35,
    },
    ui: {
      primaryColor: '#EB0029',
      secondaryColor: '#000000',
      gradientStart: '#EB0029',
      gradientEnd: '#FF6B6B',
      glowColor: '#FF4444',
      chartColor: '#EB0029',
      backgroundColor: '#1a0000',
      icon: '⬡',
    },
    portfolio: {
      defaultBalance: 1000,
      allocationType: 'secondary',
      recommendedAllocation: 3,
      riskRating: 6,
    },
    founded: 2017,
    description: 'Content entertainment blockchain',
  },
  TON: {
    id: 'ton-blockchain',
    symbol: 'TON',
    name: 'Ton',
    fullName: 'The Open Network',
    category: 'layer1',
    network: 'ton',
    wallet: {
      addressPrefix: 'EQ',
      addressLength: 48,
      decimals: 9,
      displayPrecision: 2,
      minTransfer: 0.01,
      maxTransfer: 10000,
      minDeposit: 0.1,
      minWithdrawal: 0.1,
      maxWithdrawal: 5000,
      networkFee: 0.0001,
      estimatedConfirmationTime: '5 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 7.85,
      marketCap: 26000000000,
      volume24h: 850000000,
      rank: 13,
      circulatingSupply: 3300000000,
      change24h: 3.2,
      change7d: 6.5,
      change30d: 4.1,
      volatility: 3.8,
      trend: 'bullish',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 0.1,
      maxTrade: 1000,
      profitMultipliers: [1.4, 2.1, 2.8, 3.6],
      riskLevel: 'high',
      spreadPercentage: 0.45,
    },
    ui: {
      primaryColor: '#0098EA',
      secondaryColor: '#000000',
      gradientStart: '#0098EA',
      gradientEnd: '#00C4FF',
      glowColor: '#00E5FF',
      chartColor: '#0098EA',
      backgroundColor: '#000d1a',
      icon: '◆',
    },
    portfolio: {
      defaultBalance: 50,
      allocationType: 'secondary',
      recommendedAllocation: 4,
      riskRating: 7,
    },
    founded: 2020,
    description: 'Decentralized blockchain platform',
  },
  ADA: {
    id: 'cardano',
    symbol: 'ADA',
    name: 'Cardano',
    fullName: 'Cardano',
    category: 'layer1',
    network: 'cardano',
    wallet: {
      addressPrefix: 'addr',
      addressLength: 58,
      decimals: 6,
      displayPrecision: 2,
      minTransfer: 1,
      maxTransfer: 100000,
      minDeposit: 1,
      minWithdrawal: 1,
      maxWithdrawal: 50000,
      networkFee: 0.2,
      estimatedConfirmationTime: '20 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 1.15,
      marketCap: 42000000000,
      volume24h: 1600000000,
      rank: 9,
      circulatingSupply: 36500000000,
      maxSupply: 45000000000,
      change24h: 2.3,
      change7d: 4.1,
      change30d: 0.8,
      volatility: 2.9,
      trend: 'sideways',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 1,
      maxTrade: 10000,
      profitMultipliers: [1.2, 1.7, 2.2, 2.8],
      riskLevel: 'medium',
      spreadPercentage: 0.35,
    },
    ui: {
      primaryColor: '#0D3142',
      secondaryColor: '#000000',
      gradientStart: '#0D3142',
      gradientEnd: '#1F5A72',
      glowColor: '#00C4FF',
      chartColor: '#0D3142',
      backgroundColor: '#0a1a1f',
      icon: '₳',
    },
    portfolio: {
      defaultBalance: 100,
      allocationType: 'secondary',
      recommendedAllocation: 4,
      riskRating: 5,
    },
    founded: 2015,
    description: 'Peer-reviewed blockchain platform',
  },
  AVAX: {
    id: 'avalanche',
    symbol: 'AVAX',
    name: 'Avalanche',
    fullName: 'Avalanche',
    category: 'layer1',
    network: 'avalanche',
    wallet: {
      addressPrefix: 'X-',
      addressLength: 42,
      decimals: 18,
      displayPrecision: 2,
      minTransfer: 0.001,
      maxTransfer: 10000,
      minDeposit: 0.1,
      minWithdrawal: 0.1,
      maxWithdrawal: 5000,
      networkFee: 0.001,
      estimatedConfirmationTime: '1-2 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 42.32,
      marketCap: 18000000000,
      volume24h: 890000000,
      rank: 14,
      circulatingSupply: 425000000,
      maxSupply: 720000000,
      change24h: 2.9,
      change7d: 5.8,
      change30d: 2.1,
      volatility: 3.6,
      trend: 'bullish',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 0.1,
      maxTrade: 1000,
      profitMultipliers: [1.3, 1.9, 2.6, 3.4],
      riskLevel: 'high',
      spreadPercentage: 0.4,
    },
    ui: {
      primaryColor: '#E84142',
      secondaryColor: '#000000',
      gradientStart: '#E84142',
      gradientEnd: '#FF6B6B',
      glowColor: '#FF4444',
      chartColor: '#E84142',
      backgroundColor: '#1a0000',
      icon: '▲',
    },
    portfolio: {
      defaultBalance: 10,
      allocationType: 'secondary',
      recommendedAllocation: 5,
      riskRating: 7,
    },
    founded: 2020,
    description: 'Scalable blockchain platform',
  },
  LINK: {
    id: 'chainlink',
    symbol: 'LINK',
    name: 'Chainlink',
    fullName: 'Chainlink',
    category: 'infrastructure',
    network: 'ethereum',
    wallet: {
      addressPrefix: '0x',
      addressLength: 42,
      decimals: 18,
      displayPrecision: 2,
      minTransfer: 0.1,
      maxTransfer: 100000,
      minDeposit: 1,
      minWithdrawal: 1,
      maxWithdrawal: 50000,
      networkFee: 0.01,
      estimatedConfirmationTime: '12-30 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 28.45,
      marketCap: 14000000000,
      volume24h: 650000000,
      rank: 16,
      circulatingSupply: 492000000,
      maxSupply: 1000000000,
      change24h: 3.1,
      change7d: 6.2,
      change30d: 3.8,
      volatility: 3.7,
      trend: 'bullish',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 0.5,
      maxTrade: 5000,
      profitMultipliers: [1.3, 1.8, 2.4, 3.1],
      riskLevel: 'medium',
      spreadPercentage: 0.4,
    },
    ui: {
      primaryColor: '#2A5ADA',
      secondaryColor: '#000000',
      gradientStart: '#2A5ADA',
      gradientEnd: '#5A8BFF',
      glowColor: '#00AAFF',
      chartColor: '#2A5ADA',
      backgroundColor: '#0f1a2e',
      icon: '🔗',
    },
    portfolio: {
      defaultBalance: 20,
      allocationType: 'secondary',
      recommendedAllocation: 4,
      riskRating: 6,
    },
    founded: 2017,
    description: 'Decentralized oracle network',
  },
  POL: {
    id: 'polygon',
    symbol: 'POL',
    name: 'Polygon',
    fullName: 'Polygon',
    category: 'layer2',
    network: 'polygon',
    wallet: {
      addressPrefix: '0x',
      addressLength: 42,
      decimals: 18,
      displayPrecision: 2,
      minTransfer: 0.1,
      maxTransfer: 100000,
      minDeposit: 1,
      minWithdrawal: 1,
      maxWithdrawal: 50000,
      networkFee: 0.0001,
      estimatedConfirmationTime: '2 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 0.95,
      marketCap: 9600000000,
      volume24h: 580000000,
      rank: 18,
      circulatingSupply: 10100000000,
      change24h: 2.5,
      change7d: 5.1,
      change30d: 1.9,
      volatility: 3.2,
      trend: 'bullish',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 1,
      maxTrade: 50000,
      profitMultipliers: [1.2, 1.6, 2.1, 2.7],
      riskLevel: 'medium',
      spreadPercentage: 0.3,
    },
    ui: {
      primaryColor: '#8247E5',
      secondaryColor: '#000000',
      gradientStart: '#8247E5',
      gradientEnd: '#B88EFF',
      glowColor: '#D0B0FF',
      chartColor: '#8247E5',
      backgroundColor: '#1a0f2e',
      icon: '⬡',
    },
    portfolio: {
      defaultBalance: 500,
      allocationType: 'secondary',
      recommendedAllocation: 4,
      riskRating: 6,
    },
    founded: 2017,
    description: 'Ethereum scaling solution',
  },
  SHIB: {
    id: 'shiba-inu',
    symbol: 'SHIB',
    name: 'Shiba Inu',
    fullName: 'Shiba Inu',
    category: 'memecoin',
    network: 'ethereum',
    wallet: {
      addressPrefix: '0x',
      addressLength: 42,
      decimals: 18,
      displayPrecision: 0,
      minTransfer: 1000000,
      maxTransfer: 1000000000,
      minDeposit: 1000000,
      minWithdrawal: 1000000,
      maxWithdrawal: 500000000,
      networkFee: 10000,
      estimatedConfirmationTime: '12-30 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 0.0000285,
      marketCap: 18000000000,
      volume24h: 1200000000,
      rank: 15,
      circulatingSupply: 589000000000000,
      change24h: 4.2,
      change7d: 9.1,
      change30d: 7.3,
      volatility: 5.8,
      trend: 'bullish',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 10000000,
      maxTrade: 100000000000,
      profitMultipliers: [1.7, 2.6, 3.5, 5],
      riskLevel: 'extreme',
      spreadPercentage: 0.8,
    },
    ui: {
      primaryColor: '#FF6B35',
      secondaryColor: '#000000',
      gradientStart: '#FF6B35',
      gradientEnd: '#FF9F5A',
      glowColor: '#FFB347',
      chartColor: '#FF6B35',
      backgroundColor: '#1a0a00',
      icon: '🐕',
    },
    portfolio: {
      defaultBalance: 10000000,
      allocationType: 'alternative',
      recommendedAllocation: 2,
      riskRating: 9,
    },
    founded: 2020,
    description: 'Meme token inspired by DOGE',
  },
  PEPE: {
    id: 'pepe',
    symbol: 'PEPE',
    name: 'Pepe',
    fullName: 'Pepe',
    category: 'memecoin',
    network: 'ethereum',
    wallet: {
      addressPrefix: '0x',
      addressLength: 42,
      decimals: 18,
      displayPrecision: 0,
      minTransfer: 100000,
      maxTransfer: 100000000,
      minDeposit: 100000,
      minWithdrawal: 100000,
      maxWithdrawal: 50000000,
      networkFee: 1000,
      estimatedConfirmationTime: '12-30 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 0.00000925,
      marketCap: 3800000000,
      volume24h: 450000000,
      rank: 26,
      circulatingSupply: 420690000000000,
      change24h: 5.8,
      change7d: 12.3,
      change30d: 15.2,
      volatility: 6.5,
      trend: 'bullish',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 1000000,
      maxTrade: 10000000000,
      profitMultipliers: [1.8, 2.8, 4, 5.5],
      riskLevel: 'extreme',
      spreadPercentage: 1.0,
    },
    ui: {
      primaryColor: '#00AA00',
      secondaryColor: '#000000',
      gradientStart: '#00AA00',
      gradientEnd: '#00FF00',
      glowColor: '#00FF00',
      chartColor: '#00AA00',
      backgroundColor: '#001a00',
      icon: '🐸',
    },
    portfolio: {
      defaultBalance: 1000000,
      allocationType: 'alternative',
      recommendedAllocation: 1,
      riskRating: 10,
    },
    founded: 2023,
    description: 'Pepe the Frog cryptocurrency',
  },
  DOT: {
    id: 'polkadot',
    symbol: 'DOT',
    name: 'Polkadot',
    fullName: 'Polkadot',
    category: 'layer1',
    network: 'polkadot',
    wallet: {
      addressPrefix: '1',
      addressLength: 47,
      decimals: 10,
      displayPrecision: 2,
      minTransfer: 0.1,
      maxTransfer: 10000,
      minDeposit: 1,
      minWithdrawal: 1,
      maxWithdrawal: 5000,
      networkFee: 0.1,
      estimatedConfirmationTime: '6 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 9.24,
      marketCap: 14000000000,
      volume24h: 520000000,
      rank: 17,
      circulatingSupply: 1516000000,
      change24h: 2.4,
      change7d: 4.8,
      change30d: 1.6,
      volatility: 3.1,
      trend: 'sideways',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 0.5,
      maxTrade: 5000,
      profitMultipliers: [1.2, 1.7, 2.2, 2.8],
      riskLevel: 'medium',
      spreadPercentage: 0.35,
    },
    ui: {
      primaryColor: '#E6007A',
      secondaryColor: '#000000',
      gradientStart: '#E6007A',
      gradientEnd: '#FF3399',
      glowColor: '#FF66BB',
      chartColor: '#E6007A',
      backgroundColor: '#1a0009',
      icon: '●',
    },
    portfolio: {
      defaultBalance: 50,
      allocationType: 'secondary',
      recommendedAllocation: 3,
      riskRating: 6,
    },
    founded: 2016,
    description: 'Multi-chain platform',
  },
  UNI: {
    id: 'uniswap',
    symbol: 'UNI',
    name: 'Uniswap',
    fullName: 'Uniswap',
    category: 'defi',
    network: 'ethereum',
    wallet: {
      addressPrefix: '0x',
      addressLength: 42,
      decimals: 18,
      displayPrecision: 2,
      minTransfer: 0.01,
      maxTransfer: 10000,
      minDeposit: 0.1,
      minWithdrawal: 0.1,
      maxWithdrawal: 5000,
      networkFee: 0.01,
      estimatedConfirmationTime: '12-30 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 25.82,
      marketCap: 11500000000,
      volume24h: 750000000,
      rank: 19,
      circulatingSupply: 445000000,
      maxSupply: 1000000000,
      change24h: 2.8,
      change7d: 5.5,
      change30d: 2.3,
      volatility: 3.4,
      trend: 'bullish',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 0.1,
      maxTrade: 5000,
      profitMultipliers: [1.3, 1.8, 2.4, 3.1],
      riskLevel: 'medium',
      spreadPercentage: 0.4,
    },
    ui: {
      primaryColor: '#FF007A',
      secondaryColor: '#000000',
      gradientStart: '#FF007A',
      gradientEnd: '#FF3399',
      glowColor: '#FF66BB',
      chartColor: '#FF007A',
      backgroundColor: '#1a0009',
      icon: '⊚',
    },
    portfolio: {
      defaultBalance: 10,
      allocationType: 'secondary',
      recommendedAllocation: 3,
      riskRating: 6,
    },
    founded: 2018,
    description: 'Decentralized exchange protocol',
  },
  APT: {
    id: 'aptos',
    symbol: 'APT',
    name: 'Aptos',
    fullName: 'Aptos',
    category: 'layer1',
    network: 'aptos',
    wallet: {
      addressPrefix: '0x',
      addressLength: 66,
      decimals: 8,
      displayPrecision: 2,
      minTransfer: 0.01,
      maxTransfer: 10000,
      minDeposit: 0.1,
      minWithdrawal: 0.1,
      maxWithdrawal: 5000,
      networkFee: 0.00001,
      estimatedConfirmationTime: '4 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 12.45,
      marketCap: 7200000000,
      volume24h: 380000000,
      rank: 21,
      circulatingSupply: 578000000,
      maxSupply: 1000000000,
      change24h: 3.1,
      change7d: 6.8,
      change30d: 4.2,
      volatility: 3.9,
      trend: 'bullish',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 0.1,
      maxTrade: 1000,
      profitMultipliers: [1.4, 2.1, 2.9, 3.7],
      riskLevel: 'high',
      spreadPercentage: 0.45,
    },
    ui: {
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      gradientStart: '#000000',
      gradientEnd: '#333333',
      glowColor: '#AAAAAA',
      chartColor: '#FFFFFF',
      backgroundColor: '#0a0a0a',
      icon: '▪',
    },
    portfolio: {
      defaultBalance: 50,
      allocationType: 'alternative',
      recommendedAllocation: 2,
      riskRating: 7,
    },
    founded: 2022,
    description: 'Move language blockchain',
  },
  SUI: {
    id: 'sui',
    symbol: 'SUI',
    name: 'Sui',
    fullName: 'Sui',
    category: 'layer1',
    network: 'sui',
    wallet: {
      addressPrefix: '0x',
      addressLength: 64,
      decimals: 9,
      displayPrecision: 2,
      minTransfer: 0.01,
      maxTransfer: 100000,
      minDeposit: 1,
      minWithdrawal: 1,
      maxWithdrawal: 50000,
      networkFee: 0.00001,
      estimatedConfirmationTime: '1 second',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 4.32,
      marketCap: 8900000000,
      volume24h: 420000000,
      rank: 20,
      circulatingSupply: 2060000000,
      maxSupply: 10000000000,
      change24h: 3.5,
      change7d: 7.2,
      change30d: 5.8,
      volatility: 4.1,
      trend: 'bullish',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 1,
      maxTrade: 10000,
      profitMultipliers: [1.4, 2.2, 3, 3.8],
      riskLevel: 'high',
      spreadPercentage: 0.45,
    },
    ui: {
      primaryColor: '#6FBCF0',
      secondaryColor: '#000000',
      gradientStart: '#6FBCF0',
      gradientEnd: '#9FD5FF',
      glowColor: '#00E5FF',
      chartColor: '#6FBCF0',
      backgroundColor: '#0a0f1a',
      icon: '◆',
    },
    portfolio: {
      defaultBalance: 200,
      allocationType: 'alternative',
      recommendedAllocation: 2,
      riskRating: 7,
    },
    founded: 2023,
    description: 'Move language blockchain',
  },
  XLM: {
    id: 'stellar',
    symbol: 'XLM',
    name: 'Stellar',
    fullName: 'Stellar Lumens',
    category: 'infrastructure',
    network: 'stellar',
    wallet: {
      addressPrefix: 'G',
      addressLength: 56,
      decimals: 7,
      displayPrecision: 2,
      minTransfer: 0.1,
      maxTransfer: 100000,
      minDeposit: 1,
      minWithdrawal: 1,
      maxWithdrawal: 50000,
      networkFee: 0.00001,
      estimatedConfirmationTime: '5 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 0.325,
      marketCap: 11800000000,
      volume24h: 580000000,
      rank: 18,
      circulatingSupply: 36300000000,
      maxSupply: 50000000000,
      change24h: 1.8,
      change7d: 3.5,
      change30d: -1.2,
      volatility: 2.5,
      trend: 'sideways',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 1,
      maxTrade: 50000,
      profitMultipliers: [1.1, 1.5, 1.9, 2.4],
      riskLevel: 'low',
      spreadPercentage: 0.3,
    },
    ui: {
      primaryColor: '#15F4EE',
      secondaryColor: '#000000',
      gradientStart: '#15F4EE',
      gradientEnd: '#00FF88',
      glowColor: '#00FFCC',
      chartColor: '#15F4EE',
      backgroundColor: '#001a1a',
      icon: '✦',
    },
    portfolio: {
      defaultBalance: 500,
      allocationType: 'secondary',
      recommendedAllocation: 2,
      riskRating: 4,
    },
    founded: 2014,
    description: 'Cross-border payment network',
  },
  XMR: {
    id: 'monero',
    symbol: 'XMR',
    name: 'Monero',
    fullName: 'Monero',
    category: 'privacy',
    network: 'monero',
    wallet: {
      addressPrefix: '4',
      addressLength: 95,
      decimals: 12,
      displayPrecision: 4,
      minTransfer: 0.01,
      maxTransfer: 1000,
      minDeposit: 0.1,
      minWithdrawal: 0.1,
      maxWithdrawal: 500,
      networkFee: 0.0005,
      estimatedConfirmationTime: '2 minutes',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 185.42,
      marketCap: 3200000000,
      volume24h: 125000000,
      rank: 28,
      circulatingSupply: 17250000,
      maxSupply: 18400000,
      change24h: 1.9,
      change7d: 3.8,
      change30d: -2.3,
      volatility: 2.8,
      trend: 'sideways',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: false,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 0.01,
      maxTrade: 100,
      profitMultipliers: [1.1, 1.5, 1.9, 2.3],
      riskLevel: 'medium',
      spreadPercentage: 0.5,
    },
    ui: {
      primaryColor: '#FF6600',
      secondaryColor: '#000000',
      gradientStart: '#FF6600',
      gradientEnd: '#FF9900',
      glowColor: '#FFAA00',
      chartColor: '#FF6600',
      backgroundColor: '#1a0a00',
      icon: '🔒',
    },
    portfolio: {
      defaultBalance: 1,
      allocationType: 'alternative',
      recommendedAllocation: 2,
      riskRating: 5,
    },
    founded: 2014,
    description: 'Privacy-focused cryptocurrency',
  },
  ATOM: {
    id: 'cosmos',
    symbol: 'ATOM',
    name: 'Cosmos',
    fullName: 'Cosmos',
    category: 'infrastructure',
    network: 'cosmos',
    wallet: {
      addressPrefix: 'cosmos',
      addressLength: 42,
      decimals: 6,
      displayPrecision: 2,
      minTransfer: 0.1,
      maxTransfer: 50000,
      minDeposit: 1,
      minWithdrawal: 1,
      maxWithdrawal: 25000,
      networkFee: 0.005,
      estimatedConfirmationTime: '6-7 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 14.25,
      marketCap: 12000000000,
      volume24h: 680000000,
      rank: 15,
      circulatingSupply: 843000000,
      change24h: 2.2,
      change7d: 4.6,
      change30d: 1.8,
      volatility: 3.0,
      trend: 'sideways',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 0.5,
      maxTrade: 10000,
      profitMultipliers: [1.2, 1.7, 2.2, 2.8],
      riskLevel: 'medium',
      spreadPercentage: 0.35,
    },
    ui: {
      primaryColor: '#D6D9E4',
      secondaryColor: '#000000',
      gradientStart: '#D6D9E4',
      gradientEnd: '#E8EBFF',
      glowColor: '#C0C5FF',
      chartColor: '#D6D9E4',
      backgroundColor: '#0a0d1a',
      icon: '❀',
    },
    portfolio: {
      defaultBalance: 100,
      allocationType: 'secondary',
      recommendedAllocation: 3,
      riskRating: 5,
    },
    founded: 2019,
    description: 'Interoperable blockchain ecosystem',
  },
  NEAR: {
    id: 'near-protocol',
    symbol: 'NEAR',
    name: 'NEAR',
    fullName: 'NEAR Protocol',
    category: 'layer1',
    network: 'near',
    wallet: {
      addressPrefix: '',
      addressLength: 64,
      decimals: 24,
      displayPrecision: 2,
      minTransfer: 0.00001,
      maxTransfer: 10000,
      minDeposit: 0.1,
      minWithdrawal: 0.1,
      maxWithdrawal: 5000,
      networkFee: 0.0001,
      estimatedConfirmationTime: '1-2 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 7.82,
      marketCap: 9100000000,
      volume24h: 410000000,
      rank: 19,
      circulatingSupply: 1164000000,
      change24h: 2.9,
      change7d: 5.8,
      change30d: 3.4,
      volatility: 3.6,
      trend: 'bullish',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 0.1,
      maxTrade: 1000,
      profitMultipliers: [1.3, 1.9, 2.6, 3.4],
      riskLevel: 'high',
      spreadPercentage: 0.4,
    },
    ui: {
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      gradientStart: '#000000',
      gradientEnd: '#333333',
      glowColor: '#AAAAAA',
      chartColor: '#FFFFFF',
      backgroundColor: '#0a0a0a',
      icon: '⊂⊃',
    },
    portfolio: {
      defaultBalance: 50,
      allocationType: 'alternative',
      recommendedAllocation: 2,
      riskRating: 6,
    },
    founded: 2018,
    description: 'Smart contract blockchain',
  },
  ARB: {
    id: 'arbitrum',
    symbol: 'ARB',
    name: 'Arbitrum',
    fullName: 'Arbitrum',
    category: 'layer2',
    network: 'arbitrum',
    wallet: {
      addressPrefix: '0x',
      addressLength: 42,
      decimals: 18,
      displayPrecision: 2,
      minTransfer: 0.1,
      maxTransfer: 100000,
      minDeposit: 1,
      minWithdrawal: 1,
      maxWithdrawal: 50000,
      networkFee: 0.0001,
      estimatedConfirmationTime: '1 second',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 2.18,
      marketCap: 11200000000,
      volume24h: 920000000,
      rank: 17,
      circulatingSupply: 5142000000,
      maxSupply: 10000000000,
      change24h: 2.6,
      change7d: 5.3,
      change30d: 2.1,
      volatility: 3.3,
      trend: 'bullish',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 1,
      maxTrade: 50000,
      profitMultipliers: [1.2, 1.6, 2.1, 2.7],
      riskLevel: 'medium',
      spreadPercentage: 0.3,
    },
    ui: {
      primaryColor: '#28A0F0',
      secondaryColor: '#000000',
      gradientStart: '#28A0F0',
      gradientEnd: '#5AC3FF',
      glowColor: '#00D4FF',
      chartColor: '#28A0F0',
      backgroundColor: '#0a0f1a',
      icon: '⬜',
    },
    portfolio: {
      defaultBalance: 200,
      allocationType: 'secondary',
      recommendedAllocation: 3,
      riskRating: 6,
    },
    founded: 2021,
    description: 'Layer 2 scaling solution',
  },
  OP: {
    id: 'optimism',
    symbol: 'OP',
    name: 'Optimism',
    fullName: 'Optimism',
    category: 'layer2',
    network: 'optimism',
    wallet: {
      addressPrefix: '0x',
      addressLength: 42,
      decimals: 18,
      displayPrecision: 2,
      minTransfer: 0.1,
      maxTransfer: 100000,
      minDeposit: 1,
      minWithdrawal: 1,
      maxWithdrawal: 50000,
      networkFee: 0.0001,
      estimatedConfirmationTime: '2 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 3.85,
      marketCap: 9800000000,
      volume24h: 650000000,
      rank: 22,
      circulatingSupply: 2547000000,
      maxSupply: 4294000000,
      change24h: 2.3,
      change7d: 4.8,
      change30d: 1.9,
      volatility: 3.2,
      trend: 'bullish',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 0.5,
      maxTrade: 10000,
      profitMultipliers: [1.2, 1.6, 2.1, 2.7],
      riskLevel: 'medium',
      spreadPercentage: 0.3,
    },
    ui: {
      primaryColor: '#FF0420',
      secondaryColor: '#000000',
      gradientStart: '#FF0420',
      gradientEnd: '#FF3355',
      glowColor: '#FF6688',
      chartColor: '#FF0420',
      backgroundColor: '#1a0409',
      icon: '◉',
    },
    portfolio: {
      defaultBalance: 100,
      allocationType: 'secondary',
      recommendedAllocation: 2,
      riskRating: 6,
    },
    founded: 2021,
    description: 'Layer 2 scaling solution',
  },
  ICP: {
    id: 'internet-computer',
    symbol: 'ICP',
    name: 'Internet Computer',
    fullName: 'Internet Computer',
    category: 'infrastructure',
    network: 'icp',
    wallet: {
      addressPrefix: '',
      addressLength: 63,
      decimals: 8,
      displayPrecision: 2,
      minTransfer: 0.01,
      maxTransfer: 10000,
      minDeposit: 0.1,
      minWithdrawal: 0.1,
      maxWithdrawal: 5000,
      networkFee: 0.0001,
      estimatedConfirmationTime: '1-2 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 18.45,
      marketCap: 8500000000,
      volume24h: 320000000,
      rank: 24,
      circulatingSupply: 461000000,
      change24h: 2.1,
      change7d: 4.3,
      change30d: 0.9,
      volatility: 3.4,
      trend: 'sideways',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 0.1,
      maxTrade: 2000,
      profitMultipliers: [1.3, 1.8, 2.4, 3.1],
      riskLevel: 'medium',
      spreadPercentage: 0.4,
    },
    ui: {
      primaryColor: '#29ABE2',
      secondaryColor: '#000000',
      gradientStart: '#29ABE2',
      gradientEnd: '#00E5FF',
      glowColor: '#00FFFF',
      chartColor: '#29ABE2',
      backgroundColor: '#000d1a',
      icon: '⬢',
    },
    portfolio: {
      defaultBalance: 20,
      allocationType: 'alternative',
      recommendedAllocation: 2,
      riskRating: 6,
    },
    founded: 2021,
    description: 'Decentralized cloud computing',
  },
  FIL: {
    id: 'filecoin',
    symbol: 'FIL',
    name: 'Filecoin',
    fullName: 'Filecoin',
    category: 'infrastructure',
    network: 'filecoin',
    wallet: {
      addressPrefix: 'f',
      addressLength: 62,
      decimals: 18,
      displayPrecision: 2,
      minTransfer: 0.001,
      maxTransfer: 10000,
      minDeposit: 0.1,
      minWithdrawal: 0.1,
      maxWithdrawal: 5000,
      networkFee: 0.00001,
      estimatedConfirmationTime: '30 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 18.92,
      marketCap: 8200000000,
      volume24h: 380000000,
      rank: 25,
      circulatingSupply: 433000000,
      maxSupply: 2000000000,
      change24h: 2.7,
      change7d: 5.4,
      change30d: 2.8,
      volatility: 3.5,
      trend: 'bullish',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 0.01,
      maxTrade: 1000,
      profitMultipliers: [1.3, 1.9, 2.6, 3.3],
      riskLevel: 'high',
      spreadPercentage: 0.4,
    },
    ui: {
      primaryColor: '#0090FF',
      secondaryColor: '#000000',
      gradientStart: '#0090FF',
      gradientEnd: '#00D4FF',
      glowColor: '#00FFFF',
      chartColor: '#0090FF',
      backgroundColor: '#000d1a',
      icon: '📁',
    },
    portfolio: {
      defaultBalance: 10,
      allocationType: 'alternative',
      recommendedAllocation: 2,
      riskRating: 7,
    },
    founded: 2017,
    description: 'Decentralized storage network',
  },
  VET: {
    id: 'vechain',
    symbol: 'VET',
    name: 'VeChain',
    fullName: 'VeChain',
    category: 'infrastructure',
    network: 'vechain',
    wallet: {
      addressPrefix: '0x',
      addressLength: 42,
      decimals: 18,
      displayPrecision: 0,
      minTransfer: 1,
      maxTransfer: 1000000,
      minDeposit: 100,
      minWithdrawal: 100,
      maxWithdrawal: 500000,
      networkFee: 0.001,
      estimatedConfirmationTime: '10 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 0.115,
      marketCap: 12500000000,
      volume24h: 420000000,
      rank: 16,
      circulatingSupply: 108500000000,
      maxSupply: 87000000000,
      change24h: 1.8,
      change7d: 3.5,
      change30d: -1.5,
      volatility: 2.6,
      trend: 'sideways',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 100,
      maxTrade: 1000000,
      profitMultipliers: [1.1, 1.5, 1.9, 2.4],
      riskLevel: 'low',
      spreadPercentage: 0.3,
    },
    ui: {
      primaryColor: '#39A0CA',
      secondaryColor: '#000000',
      gradientStart: '#39A0CA',
      gradientEnd: '#5AC3FF',
      glowColor: '#00D4FF',
      chartColor: '#39A0CA',
      backgroundColor: '#0a0f1a',
      icon: '✓',
    },
    portfolio: {
      defaultBalance: 5000,
      allocationType: 'secondary',
      recommendedAllocation: 2,
      riskRating: 4,
    },
    founded: 2015,
    description: 'Supply chain blockchain',
  },
  HBAR: {
    id: 'hedera',
    symbol: 'HBAR',
    name: 'Hedera',
    fullName: 'Hedera Hashgraph',
    category: 'layer1',
    network: 'hedera',
    wallet: {
      addressPrefix: '0.0.',
      addressLength: 20,
      decimals: 8,
      displayPrecision: 2,
      minTransfer: 0.01,
      maxTransfer: 100000,
      minDeposit: 1,
      minWithdrawal: 1,
      maxWithdrawal: 50000,
      networkFee: 0.0001,
      estimatedConfirmationTime: '3-5 seconds',
      qrCodeSupported: true,
    },
    marketData: {
      currentPrice: 0.185,
      marketCap: 7200000000,
      volume24h: 180000000,
      rank: 27,
      circulatingSupply: 38900000000,
      maxSupply: 50000000000,
      change24h: 1.5,
      change7d: 3.2,
      change30d: -2.1,
      volatility: 2.3,
      trend: 'sideways',
      lastUpdated: new Date().toISOString(),
    },
    trading: {
      buyEnabled: true,
      sellEnabled: true,
      swapEnabled: true,
      tradingEnabled: true,
      supportedDurations: [1, 5, 15, 60],
      minTrade: 1,
      maxTrade: 50000,
      profitMultipliers: [1.1, 1.5, 1.9, 2.3],
      riskLevel: 'low',
      spreadPercentage: 0.3,
    },
    ui: {
      primaryColor: '#000000',
      secondaryColor: '#FFFFFF',
      gradientStart: '#000000',
      gradientEnd: '#333333',
      glowColor: '#AAAAAA',
      chartColor: '#FFFFFF',
      backgroundColor: '#0a0a0a',
      icon: '▲',
    },
    portfolio: {
      defaultBalance: 1000,
      allocationType: 'alternative',
      recommendedAllocation: 1,
      riskRating: 4,
    },
    founded: 2017,
    description: 'Enterprise-grade blockchain',
  },
};

export const CRYPTO_LIST = Object.values(CRYPTOCURRENCIES);

export function getCryptoByCryptodeysymbol(symbol: string): Cryptocurrency | undefined {
  return CRYPTOCURRENCIES[symbol];
}

export function getStablecoins(): Cryptocurrency[] {
  return CRYPTO_LIST.filter(crypto => crypto.category === 'stablecoin');
}

export function getMemecoins(): Cryptocurrency[] {
  return CRYPTO_LIST.filter(crypto => crypto.category === 'memecoin');
}

export function getDefiTokens(): Cryptocurrency[] {
  return CRYPTO_LIST.filter(crypto => crypto.category === 'defi');
}

export function sortByMarketCap(): Cryptocurrency[] {
  return [...CRYPTO_LIST].sort((a, b) => b.marketData.marketCap - a.marketData.marketCap);
}

export function sortByPrice(): Cryptocurrency[] {
  return [...CRYPTO_LIST].sort((a, b) => b.marketData.currentPrice - a.marketData.currentPrice);
}

export function getGainers(): Cryptocurrency[] {
  return CRYPTO_LIST.filter(crypto => crypto.marketData.change24h > 2);
}

export function getLosers(): Cryptocurrency[] {
  return CRYPTO_LIST.filter(crypto => crypto.marketData.change24h < -2);
}

export default CRYPTOCURRENCIES;